# Generate hotkeys.py from the model's VTube Studio config.
#
# The 52 bindings are transcribed by machine, never by hand -- the trigger slots are
# position-independent (橡皮 sits in Trigger2, not Trigger1) and a hand copy would
# quietly drop entries.
#
# Two traps this encodes:
#   * N1-N4 are the MAIN-ROW digits 1-4, not the numpad. VTS also has Numpad1-Numpad4
#     in the same list; both spellings coexist as separate literals in the binary.
#     Hotkey 33 is Alt+N (letter N) and must not be confused with 42/47/48/50.
#   * LeftMouseButton is bound by 4 different actions. The window is 320px square, so
#     VTS's hit-area discrimination does not carry over; pet.py cycles them per click.
#
# Run:  python gen_hotkeys.py

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import modelmap

# 作者原版的 c_0120.vtube.json（那个文件里有全部 52 条快捷键绑定，照它转写）。
# 默认去仓库里的 model-src\ 找，见 gen_model3.py 顶部那段说明；也可以用
# 环境变量 MODEL_SRC 指别处。
SRC = os.path.join(os.environ.get("MODEL_SRC") or os.path.join(HERE, "model-src"),
                   "c_0120.vtube.json")

# VTS trigger names -> Windows virtual-key codes.
# "Alt" is VK_MENU, which reads true when either Alt is held.
VK = {
    "Alt": 0x12, "LeftControl": 0xA2, "RightControl": 0xA3,
    "LeftShift": 0xA0, "RightShift": 0xA1,
    "PageUp": 0x21, "PageDown": 0x22, "Delete": 0x2E,
    "Decimal": 0x6E, "Multiply": 0x6A,
}
for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
    VK[c] = ord(c)
for d in "123456789":
    VK[d] = ord(d)                      # main-row digits
for n in range(10):
    VK["Numpad%d" % n] = 0x60 + n       # numpad digits
# VTS writes main-row digits as N0-N9. Verified by extracting the NUL-delimited
# strings from Assembly-CSharp.dll: N0-N9 and Numpad0-Numpad9 are separate literals,
# so these are NOT the numpad keys despite the similar spelling.
for d in "0123456789":
    VK["N" + d] = ord(d)

CLICK = "LeftMouseButton"


def main():
    if not os.path.isfile(SRC):
        raise SystemExit(
            "找不到作者原版的 c_0120.vtube.json：%s\n"
            "把作者模型包 DS鲸鱼娘.zip 里的 DS鼠控版.zip 解压到 %s，"
            "或者用环境变量 MODEL_SRC 指过去。" % (SRC, os.path.dirname(SRC)))
    with open(SRC, encoding="utf-8") as fh:
        cfg = json.load(fh)

    exprs = []      # ToggleExpression
    motions = []    # TriggerAnimation
    resets = []     # RemoveAllExpressions
    click = []      # bound to LeftMouseButton
    problems = []

    for h in cfg["Hotkeys"]:
        t = h["Triggers"]
        names = [t.get("Trigger%d" % i, "") for i in (1, 2, 3)]
        names = [n for n in names if n]
        if not names:
            problems.append("no trigger: %s" % h["Name"])
            continue

        fname = h.get("File", "")
        label = modelmap.VTS_FILE.get(fname)
        action = h["Action"]

        if action == "ToggleExpression":
            kind = "expr"
        elif action == "TriggerAnimation":
            kind = "motion"
        elif action == "RemoveAllExpressions":
            kind = "reset"
        else:
            problems.append("unknown action %r: %s" % (action, h["Name"]))
            continue

        if kind != "reset" and label is None:
            problems.append("unmapped File %r (%s)" % (fname, h["Name"]))
            continue

        if names == [CLICK]:
            click.append((kind, label, h["Name"]))
            continue

        keys = []
        for n in names:
            if n == CLICK:
                problems.append("mixed mouse+key combo: %s" % h["Name"])
                continue
            if n not in VK:
                problems.append("unknown key %r (%s)" % (n, h["Name"]))
                continue
            keys.append(VK[n])
        if len(keys) != len(names):
            continue

        entry = {"name": h["Name"], "keys": tuple(sorted(keys)), "kind": kind,
                 "label": label, "raw": names}
        (exprs if kind == "expr" else motions if kind == "motion" else resets).append(entry)

    # ---- emit ----
    out = os.path.join(HERE, "hotkeys.py")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write('"""GENERATED by gen_hotkeys.py - do not edit by hand.\n\n')
        fh.write('Bindings transcribed from c_0120.vtube.json.\n"""\n\n')
        fh.write("# A binding fires when every key in `keys` is held. Keys are VK codes\n")
        fh.write("# (see gen_hotkeys.py); matching is order-independent, and the keys are\n")
        fh.write("# never swallowed, so they still reach the foreground app.\n")
        fh.write("HOTKEYS = [\n")
        for e in exprs + motions + resets:
            fh.write("    {'name': %r, 'keys': %r, 'kind': %r, 'label': %r},\n"
                     % (e["name"], e["keys"], e["kind"], e["label"]))
        fh.write("]\n\n")
        fh.write("# Clicking the pet cycles these, since a 320px window cannot tell the\n")
        fh.write("# hit areas apart the way VTS did.\n")
        fh.write("CLICK_CYCLE = [\n")
        for kind, label, name in click:
            fh.write("    {'name': %r, 'kind': %r, 'label': %r},\n" % (name, kind, label))
        fh.write("]\n")

    print("wrote", out)
    print("  expressions :", len(exprs))
    print("  motions     :", len(motions))
    print("  resets      :", len(resets))
    print("  click cycle :", len(click), [c[2] for c in click])
    if problems:
        print("  PROBLEMS:")
        for x in problems:
            print("    -", x)
    missing = [e["name"] for e in exprs if e["label"] not in modelmap.EXPR_ID]
    if missing:
        print("  labels not in modelmap.EXPR_ID:", missing)
    bad = [e["name"] for e in motions if e["label"] not in modelmap.MOTION]
    if bad:
        print("  labels not in modelmap.MOTION:", bad)


if __name__ == "__main__":
    main()
