"""GENERATED by gen_hotkeys.py - do not edit by hand.

Bindings transcribed from c_0120.vtube.json.
"""

# A binding fires when every key in `keys` is held. Keys are VK codes
# (see gen_hotkeys.py); matching is order-independent, and the keys are
# never swallowed, so they still reach the foreground app.
HOTKEYS = [
    {'name': '撤回', 'keys': (90, 162), 'kind': 'expr', 'label': '撤回'},
    {'name': '橡皮', 'keys': (69,), 'kind': 'expr', 'label': '橡皮'},
    {'name': '蛋包饭', 'keys': (98, 110), 'kind': 'expr', 'label': '蛋包饭'},
    {'name': '冒爱心动画', 'keys': (104, 110), 'kind': 'expr', 'label': 'love'},
    {'name': '喵喵手~喵~动画', 'keys': (103, 110), 'kind': 'expr', 'label': '喵喵手~喵~动画'},
    {'name': '双手比耶', 'keys': (105, 110), 'kind': 'expr', 'label': '双手比耶'},
    {'name': '兔兔贴纸', 'keys': (18, 66), 'kind': 'expr', 'label': '兔兔贴纸'},
    {'name': '吐魂', 'keys': (18, 77), 'kind': 'expr', 'label': '吐魂'},
    {'name': '呆呆眼', 'keys': (18, 82), 'kind': 'expr', 'label': '呆呆眼'},
    {'name': '哭', 'keys': (18, 89), 'kind': 'expr', 'label': '哭'},
    {'name': '圆眼镜', 'keys': (18, 74), 'kind': 'expr', 'label': '圆眼镜'},
    {'name': '墨镜', 'keys': (18, 90), 'kind': 'expr', 'label': '墨镜'},
    {'name': '开心兴奋', 'keys': (18, 85), 'kind': 'expr', 'label': '开心兴奋'},
    {'name': '心跳', 'keys': (18, 67), 'kind': 'expr', 'label': '心跳'},
    {'name': '悲伤', 'keys': (18, 81), 'kind': 'expr', 'label': '悲伤'},
    {'name': '情绪花花', 'keys': (18, 88), 'kind': 'expr', 'label': '情绪花花'},
    {'name': '感叹号', 'keys': (18, 72), 'kind': 'expr', 'label': '感叹号'},
    {'name': '方眼镜', 'keys': (18, 75), 'kind': 'expr', 'label': '方眼镜'},
    {'name': '星星眼', 'keys': (18, 87), 'kind': 'expr', 'label': '星星眼'},
    {'name': '晕晕', 'keys': (18, 73), 'kind': 'expr', 'label': '晕晕'},
    {'name': '椭圆眼镜', 'keys': (18, 76), 'kind': 'expr', 'label': '椭圆眼镜'},
    {'name': '流汗', 'keys': (18, 71), 'kind': 'expr', 'label': '流汗'},
    {'name': '爱心眼', 'keys': (18, 69), 'kind': 'expr', 'label': '爱心眼'},
    {'name': '猫猫贴纸', 'keys': (18, 86), 'kind': 'expr', 'label': '猫猫贴纸'},
    {'name': '生气', 'keys': (18, 79), 'kind': 'expr', 'label': '生气'},
    {'name': '脸红', 'keys': (18, 68), 'kind': 'expr', 'label': '脸红'},
    {'name': '蝴蝶结贴纸', 'keys': (18, 78), 'kind': 'expr', 'label': '蝴蝶结贴纸'},
    {'name': '调皮', 'keys': (18, 80), 'kind': 'expr', 'label': '调皮'},
    {'name': '闭眼口水', 'keys': (18, 84), 'kind': 'expr', 'label': '闭眼口水'},
    {'name': '问号', 'keys': (18, 70), 'kind': 'expr', 'label': '问号'},
    {'name': '阴暗', 'keys': (18, 83), 'kind': 'expr', 'label': '阴暗'},
    {'name': '使巴菲消失', 'keys': (99, 106), 'kind': 'expr', 'label': '巴菲'},
    {'name': '魔爪', 'keys': (100, 106), 'kind': 'expr', 'label': '魔爪'},
    {'name': '魔爪换色', 'keys': (101, 106), 'kind': 'expr', 'label': '魔爪换色'},
    {'name': '头箍', 'keys': (18, 51), 'kind': 'expr', 'label': '头箍'},
    {'name': '吐舌', 'keys': (77, 163), 'kind': 'expr', 'label': '吐舌'},
    {'name': '手机换色', 'keys': (96, 98), 'kind': 'expr', 'label': '手机换色'},
    {'name': '深色桌布', 'keys': (18, 52), 'kind': 'expr', 'label': '深色桌布'},
    {'name': '鲸鱼', 'keys': (18, 49), 'kind': 'expr', 'label': '鲸鱼'},
    {'name': '单边马尾', 'keys': (18, 50), 'kind': 'expr', 'label': '单边马尾'},
    {'name': '鲸鱼放桌上', 'keys': (97, 110), 'kind': 'expr', 'label': '鲸鱼放桌上'},
    {'name': '挤番茄酱动画', 'keys': (99, 110), 'kind': 'motion', 'label': '番茄酱'},
    {'name': '自拍手机', 'keys': (100, 110), 'kind': 'motion', 'label': '开盖'},
    {'name': '快速自拍', 'keys': (101, 110), 'kind': 'motion', 'label': '自拍'},
    {'name': '自拍动画', 'keys': (102, 110), 'kind': 'motion', 'label': '自拍简单'},
    {'name': '重锤出击', 'keys': (46, 163), 'kind': 'motion', 'label': 'aidale'},
    {'name': '泡泡糖', 'keys': (33, 163), 'kind': 'motion', 'label': 'chuipaopao'},
    {'name': '按键归位', 'keys': (33, 34), 'kind': 'reset', 'label': None},
]

# Clicking the pet cycles these, since a 320px window cannot tell the
# hit areas apart the way VTS did.
CLICK_CYCLE = [
    {'name': '点菜按下', 'kind': 'expr', 'label': '点菜按下'},
    {'name': '画笔', 'kind': 'expr', 'label': '画笔'},
    {'name': 'MoeMoeQ~', 'kind': 'expr', 'label': '挤'},
    {'name': '鲸鱼喷水', 'kind': 'motion', 'label': '喷水'},
]
